export default [
  'B5 + Y5 + D5 = Obsidian (Rare)',
  'G5 + E5 + Q5 = Agate (Rare)',
  'R5 + R4 + P5 = Burning Stone (Rare)',
  'E1 + E2 + E3 + E4 + E5 = E.Home (Epic)',
  'R5 + R5 + R5 + R5 = The Great Stone (Legendary)',
  'B5 + R5 + G5 = Fantastic Miss Shrimp (Rare)',
  'B1 + B2 + B3 + B4 + B5 = Subzero (Epic)',
  'G5 + G5 + G5 + G5 = The Cerberus (Legendary)',
  'B5 + D5 + D5 + Y5 + Y5 = Obelisk (Legendary)',
  'G5 + E5 + Q5 + E5 + B5 = Hayate (Legendary)',
  'R5 + R5 + R5 + P5 + Q5 = Doom (Legendary)',
  'G5 + G5 + G5 + B5 + Y5 = Darkness Stone (Legendary)',
  'P5 + P5 + P5 + D5 + Q5 = Behemoth (Legendary)',
  'R6 + D6 + Y6 + G6 + Q6 + E6 + B6 + P6 = Mokujin (Rare) (*not one shot combination)',
  'E5 + E5 + D5 + D5 + Q5 = Ultimate Hyperstone (Legendary)',
  'G5 + G5 + B5 + E5 = Big Jade (Epic)',
  'G5 + G5 + R5 + P5 = Master Quartz (Epic)',
  'Big Jade + Master Quartz + G6 = Lucky Emperor (Legendary) (*not one shot combination)',
  'B5 + B5 + B5 + Y5 + R5 = Pool of the NorthSiberian (Legendary)',
  'B5 + B5 + B5 + B5 = The Grizzly Pedant (Legendary)',
  'D5 + D5 + D5 + D5 = The Genbu SeaMaster (Legendary)',
  'Y5 + Y5 + Y5 + Y5 = The Starlet Octophus (Legendary)',
  'Q5 + Q5 + Q5 + Q5 = The Ancient Tsathoggua (Legendary)'
];